{% set name = "heudiconv" %}
{% set version = "1.1.0" %}
{% set sha256 = "cd12d174fdcba72b47093ade8613d8326267b2ce6fea88e39083ee07c7ca479c" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  entry_points:
    - heudiconv=heudiconv.cli.run:main
    - heudiconv_monitor=heudiconv.cli.monitor:main
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python

requirements:
  host:
    - python >=3.6
    - nibabel
    - nipype
    - pathlib
    - pip
    - pydicom
    - versioningit
  run:
    - python >=3.6
    - bz2file
    - dcm2niix
    - dcmstack
    - nibabel
    - nipype
    - pathlib
    - pydicom
    - rdflib
test:
  imports:
    - heudiconv
    - heudiconv.cli
    - heudiconv.external
    - heudiconv.external.tests
    - heudiconv.heuristics
  commands:
    - heudiconv --help

about:
  home: https://github.com/nipy/heudiconv
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Heuristic DICOM Converter
  description: 'Convert DICOM dirs based on heuristic info - HeuDiConv uses the dcmstack package and dcm2niix tool to convert DICOM directories or tarballs into collections of NIfTI files following pre-defined heuristic(s). '
  doc_url: https://github.com/nipy/heudiconv
  dev_url: https://github.com/nipy/heudiconv

extra:
  recipe-maintainers:
    - kastman
    - yarikoptic
    - mgxd
